version: '3.1'

services:
  db:
    image: postgres:15
    env_file:
      - .env
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  odoo:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    env_file:
      - .env
    volumes:
      - ./addons:/mnt/extra-addons
      - ./data/filestore:/var/lib/odoo/filestore

volumes:
  pgdata: